name: CMake

on:

  push:
    paths:
      - src/**
      - "CMakeLists.txt"
      - .github/workflows/cmake.yml

  pull_request:
    paths:
      - src/**
      - "CMakeLists.txt"
      - .github/workflows/**
      - .github/workflows/cmake.yml

jobs:

  linux:
    name: "Ubuntu 22.04LTS x86_64"

    runs-on: ubuntu-22.04

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure CMake
        env:
          CMAKE_PREFIX_PATH: ${{env.Qt5_Dir}}
        run: >-
          cmake .

      - name: Build
        run: |
          cmake --build . && mkdir artifact && mv 86boxman artifact

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: '86boxman Ubuntu 22.04LTS x86_64'
          path: artifact

  windows:
    name: "Windows x86_64 (MXE)"

    runs-on: ubuntu-20.04

    env:
      MXE_TARGET: x86-64-w64-mingw32.static
      MXE_CMAKE: /usr/lib/mxe/usr/bin/x86_64-w64-mingw32.static-cmake

    steps:
      - name: Install MXE Packages
        run: |
          sudo apt-get -y install software-properties-common lsb-release cmake
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 86B72ED9
          sudo add-apt-repository -y "deb [arch=amd64] https://pkg.mxe.cc/repos/apt `lsb_release -sc` main"
          sudo apt update
          sudo apt-get -y install mxe-${MXE_TARGET}-cc mxe-${MXE_TARGET}-cmake-conf mxe-${MXE_TARGET}-qt5

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure CMake
        run: >-
          ${MXE_CMAKE} .

      - name: Build
        run: |
          ${MXE_CMAKE} --build . && mkdir artifact && mv 86boxman.exe artifact

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: '86boxman Windows x86_64 (MXE)'
          path: artifact